import { apiConst } from "./apiConst";

export const UrlTypes = {
  SignUp: apiConst.Registration + "NewRegistration",
  VerifyOTP: apiConst.Registration + "OTPVerify",
  SetPIN: apiConst.Registration + "SetPIN",
  Login: apiConst.Login + "Authentication",
  ForgotPassword: apiConst.Login + "ForgotPassword",
  ResetPassword: apiConst.Login + "ResetPassword",
  GetDashboard: apiConst.Dashboard + "DashboardItem",
  GetCourseType: apiConst.courseType + "GetAll",
  GetInstituteById: apiConst.courseTypeInstitutions + "GetByCourseCategoryID",
  GetCourseByInstituteId: apiConst.course + "GetByID",
  GetStudent: apiConst.student + "GetAllStudent",
  AddNewStudent: apiConst.student + "Save",
  UpdateStudent: apiConst.student + "UpdateStudent",
  GetSubjectByCourseAndInstitutionsID: apiConst.subject + "GetByID",
  GetChapterBySubjectID: apiConst.chapter + "GetBySubjectId",
  GetTopicByChapterID: apiConst.topic + "GetByChapterId",
  GetVideoSessionByTopicID: apiConst.VideoSession + "GetVideoSessionByTopicID",
  getPlanDetails: apiConst.courseFee + "GetCourseFee",
  SkipForTrial: apiConst.Subscription + "SkipForTrial",
  GetUserProfile: apiConst.Registration + "RegistrationDetails",
  CreateOrder: apiConst.order + "CreateOrder",
  UpdateOrder: apiConst.payment + "SavePayment",
};
